__SHIFT=0
TAGTYPE_POS_INHERIT=0<<__SHIFT 		# dummy exporting should shaw this in the same paragraph
TAGTYPE_POS_INLINE=0<<__SHIFT 		# alias to INHERIT
TAGTYPE_POS_BLOCK=1<<__SHIFT 		# in a separated block eg. <div></div>
TAGTYPE_POS_FOOTNOTE=2<<__SHIFT 	# marked text does not flow normally, but accumelated in the tail
TAGTYPE_POS_HIDDEN=3<<__SHIFT 		# dummy exporting should not show any content
TAGTYPE_POS_MASK=3<<__SHIFT
# NOTE: validaty of data: only one tag may carry TAGTYPE_POS_* other than TAGTYPE_POS_INHERIT
__SHIFT+=2
TAGTYPE_IX_NORMAL=0<<__SHIFT 		# content should be indexed normally
TAGTYPE_IX_TAG=1<<__SHIFT 		# add this tag name into index tags list, if it has a param append it to the tag name
TAGTYPE_IX_RESERVED=2<<__SHIFT 		# RESERVED
TAGTYPE_IX_RESERVED2=3<<__SHIFT 	# RESERVED
TAGTYPE_IX_MASK=3<<__SHIFT
__SHIFT+=2
TAGTYPE_RESERVED1=(1<<16)-(1<<__SHIFT)
__SHIFT=16
# the following flags are Or-ed in a node-wide (not tag-wide)
TAGTYPE_FLAGS_EXTERNAL_SOURCE=1<<__SHIFT 	# some external source pointed by param
TAGTYPE_FLAGS_BYBOT=2<<__SHIFT 			# the content and descendant nodes are generated by a bot, CHANGES WILL BE LOST
TAGTYPE_FLAGS_HEADER=4<<__SHIFT 		# index content in a separated document then consume content
TAGTYPE_FLAGS_IX_FIELD=8<<__SHIFT 		# index content (again) in a separated document without consuming content
TAGTYPE_FLAGS_IX_SKIP=16<<__SHIFT 		# don't index content
TAGTYPE_FLAGS_PAD_CONTENT=32<<__SHIFT 		# append a space/LF after content
TAGTYPE_FLAGS_MASK=63<<__SHIFT

# NOTE: validaty of data: a node of type TAGTYPE_FLAGS_HEADER can't be a child of TAGTYPE_FLAGS_IX_FIELD
# NOTE: validaty of data: both TAGTYPE_FLAGS_IX_SKIP and TAGTYPE_FLAGS_IX_FIELD should not be applied to the same node
# NOTE: validaty of data: both TAGTYPE_FLAGS_HEADER and TAGTYPE_FLAGS_IX_FIELD will case redudancy if applied to same node (as things will be indexed twice without any befinit)
